// Generated by CoffeeScript 1.8.0
(function() {
  var ArrayStream, JSONStream,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  JSONStream = require('./jsonStream');

  ArrayStream = (function(_super) {
    __extends(ArrayStream, _super);

    function ArrayStream() {
      return ArrayStream.__super__.constructor.apply(this, arguments);
    }

    ArrayStream.prototype._startChar = "[";

    ArrayStream.prototype._endChar = "]";

    ArrayStream.prototype.write = function(data) {
      if (this.finished) {
        throw new Error("Can't write to finished ArrayStream");
      }
      if (typeof data === "undefined") {
        data = null;
      }
      this.enqueue({
        data: data
      });
      return this;
    };

    ArrayStream.prototype.startItem = function() {};

    return ArrayStream;

  })(JSONStream);

  module.exports = ArrayStream;

}).call(this);
