// Generated by CoffeeScript 1.8.0
(function() {
  var JSONStream, ObjectStream, util,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  JSONStream = require('./jsonStream');

  util = require('./util');

  ObjectStream = (function(_super) {
    __extends(ObjectStream, _super);

    function ObjectStream() {
      return ObjectStream.__super__.constructor.apply(this, arguments);
    }

    ObjectStream.prototype._startChar = "{";

    ObjectStream.prototype._endChar = "}";

    ObjectStream.prototype.write = function(key, data) {
      if (this.finished) {
        throw new Error("Can't write to finished ObjectStream");
      }
      if (typeof data === "undefined") {
        return;
      }
      this.enqueue({
        key: key,
        data: data
      });
      return this;
    };

    ObjectStream.prototype.startItem = function(item) {
      return this.push("\"" + (util.escapeForJSON(item.key)) + "\":");
    };

    return ObjectStream;

  })(JSONStream);

  module.exports = ObjectStream;

}).call(this);
